HMS/HMSWeb.MVC/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectClassLibrary;
using HMS.Services;

namespace HMSWeb.MVC.Controllers
{
    public class BookingsController : Controller
    {
        private hmsprojectEntities db = new hmsprojectEntities();
        private readonly ICustomer cust;

        public BookingsController(ICustomer cust)
        {
            this.cust = cust;
        }

        // GET: Bookings
        public ActionResult Index()
        {
            int id = (int)Session["id"];
            var bookings = db.Bookings.Where(b => b.CustomerId == id).ToList();

            return View(bookings);
        }

        // GET: Bookings/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = await db.Bookings.FindAsync(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Firstname");
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "RoomType");
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "BookingId,RoomId,CustomerId,checkIn,checkOut,BookedOn,payment")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Bookings.Add(booking);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Firstname", booking.CustomerId);
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "RoomType", booking.RoomId);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = await db.Bookings.FindAsync(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Firstname", booking.CustomerId);
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "RoomType", booking.RoomId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "BookingId,RoomId,CustomerId,checkIn,checkOut,BookedOn,payment")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Firstname", booking.CustomerId);
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "RoomType", booking.RoomId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = await db.Bookings.FindAsync(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Booking booking = await db.Bookings.FindAsync(id);
            db.Bookings.Remove(booking);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Bookings/Create
        public ActionResult RoomBook(string type, string Description, int? cost)
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Firstname", Session["id"]);
            Session["RoomType"] = type;
            ViewBag.Description = Description;
            ViewBag.Cost = cost;
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RoomBook(Booking booking,string payment,string fromDate,string toDate)
        {
            booking.RoomType = (string)Session["RoomType"];
            booking.payment = Convert.ToDecimal(payment);
            booking.checkIn = Convert.ToDateTime(fromDate);
            booking.checkOut= Convert.ToDateTime(toDate);


            var i = cust.Overlaps(booking);

            booking.RoomId = i.RoomId;
            booking.BookedOn = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Bookings.Add(booking);
                Customer customer = await db.Customers.FindAsync(booking.CustomerId);
                customer.Wallet = customer.Wallet - (long)Convert.ToDecimal(payment);
                db.Entry(customer).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Firstname", booking.CustomerId);
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "RoomType", booking.RoomId);
            return View(booking);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HMS/HMSWeb.MVC/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectClassLibrary;
using HMS.Services;

namespace HMSWeb.MVC.Controllers
{
    public class CustomersController : Controller
    {
        private hmsprojectEntities db = new hmsprojectEntities();
        private readonly ICustomer cust;

        public CustomersController(ICustomer cust)
        {
            this.cust = cust;
        }

        // GET: Customers
        public async Task<ActionResult> Index()
        {
            return View(await db.Customers.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = await db.Customers.FindAsync(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                customer.Wallet = 20000;
                db.Customers.Add(customer);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "HMSCustomer");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = await db.Customers.FindAsync(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("CustomerHome", "HMSCustomer");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = await db.Customers.FindAsync(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Customer customer = await db.Customers.FindAsync(id);
            db.Customers.Remove(customer);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }



        // GET: Customers/Edit/5
        public async Task<ActionResult> PasEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = await db.Customers.FindAsync(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PasEdit(Customer customer, int id)
        {

            if (ModelState.IsValid)
            {
               bool res = cust.ChangePas(customer, id);
                if (res)
                {
                    ViewBag.res = "Successfully Edited";
                }

                //var cust = new Customer() { CustomerId = id, Password = customer.Password };
                //db.Customers.Attach(cust);
                //db.Entry(cust).Property(x => x.Password).IsModified = true;
                //await db.SaveChangesAsync();
                return RedirectToAction("CustomerHome", "HMSCustomer");

            }
            return View(customer);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HMS/HMSWeb.MVC/Views/Shared/DashBoardMaster.cshtml
@*<!DOCTYPE html>
    <html lang="en">
    <head>
        <title>My Dashboard </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="~/Content/MyDashBoard.css" rel="stylesheet" />
        <link href="~/Content/DropDownButton.css" rel="stylesheet" />
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/jquery-3.3.1.min.js"></script>
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        @RenderSection("Scripts", false);
    </head>

    <body>

        <div class="jumbotron">
            <div class="container text-center">
                <h1>My DashBoard</h1>
                <p>Hello @Session["name"].ToString() !!!!!!</p>
                <p>Welcome to Hotel Management</p>
            </div>
        </div>

        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                        <span class="glyphicon glyphicon-home"></span>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>

                            <div class="dropdown">
                                <button class="dropbtn"><span class="glyphicon glyphicon-user"></span></button>
                                <div class="dropdown-content">
                                    <a href="@Url.Action("Edit","Customers", new {id = @Session["id"].ToString() })">Edit Account</a>
                                    <a href="@Url.Action("PasEdit","Customers", new {id = @Session["id"].ToString() })">Change Password</a>
                                    <a href="@Url.Action("Logout","HMSCustomer")">Logout</a>
                                </div>
                            </div>


                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div>
            @RenderBody()
        </div>

        <footer class="container-fluid text-center">
            <p>Hotel Management Copyright</p>
            <form class="form-inline">
                Get deals:
                <input type="email" class="form-control" size="50" placeholder="Email Address">
                <button type="button" class="btn btn-danger">Sign Up</button>
            </form>
        </footer>

    </body>
    </html>*@




<!DOCTYPE html>
<html lang="en">
<head>

    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/MyDashBoard.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
    @RenderSection("Scripts", false);
</head>
<body style="background-image: url('https://www.pvparadiserentals.com/wp-content/uploads/2017/10/casa-papelillos-cover.jpg');">
    @*<body style="background-image: url('../../Content/db.jpg');">*@

    <link href="~/Content/dashboardStylesheet.css" rel="stylesheet" />
    <link href="~/Content/DropDownButton.css" rel="stylesheet" />
    <style>
        .jumbotron {
            margin-top: 15px;
            padding: 17px;
            color: #C9A891;
            background-size: cover;
            background-color: #2B1B17;
            opacity: 0.1;
            font-family: 'Great Vibes', cursive;
            font-size: xx-large;
            opacity: 0.7;
        }
        p {
        color:aliceblue;
        }



    </style>

    <div class="jumbotron">
        <div class="container text-center">
            <h1>Welcome to Shangri La</h1>
            <p>Hello @Session["name"].ToString() !</p>
        </div>
    </div>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>*@
                @*<a class="navbar-brand" href="@Url.Action("Index","Home")">
                        <span class="glyphicon glyphicon-home"></span>Logo
                    </a>*@
            </div>

            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <div>
                            <button class="but" onclick="location.href='@Url.Action("CustomerHome", "HMSCustomer")'"> <span class="glyphicon glyphicon-home"></span></button>   @*<a href="#">Home</a>*@
                        </div>

                    </li>

                    <li class=" active">

                        <div class="dropdown">
                            <button class="but">Types Of Rooms</button>
                            <div class="dropdown-content">
                                <a href="@Url.Action("SuperDeluex","Home")">Super Deluxe</a>
                                <a href="@Url.Action("Deluex","Home")">Deluxe</a>
                                <a href="@Url.Action("Normal","Home")">Normal</a>
                            </div>
                        </div>

                    </li>
                    <li>
                        <button class="but" onclick="location.href='@Url.Action("Index","Bookings")'">My Bookings</button>

                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <div class="dropdown" align="left">
                            <button class="but" align="left"><span class="glyphicon glyphicon-user"></span></button>
                            <div class="dropdown-content" align="left">
                                <a href="@Url.Action("Edit","Customers", new {id = @Session["id"].ToString() })">Edit Account</a>
                                <a href="@Url.Action("PasEdit","Customers", new {id = @Session["id"].ToString() })">Change Password</a>
                                <a href="@Url.Action("Logout","HMSCustomer")">Logout</a>
                            </div>
                        </div>


                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>

</body>
</html>

HMS/HMSWeb.MVC/Views/Shared/SamLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>CSS Website Layout</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="~/Content/StyleSheet1.css" rel="stylesheet" />
</head>
<body>

    <div class="header">
        <h1>Header</h1>
    </div>

    <div class="topnav">
        <a href="#">Link</a>
        <a href="#">Link</a>
        <a href="#">Link</a>
    </div>

    

    @RenderBody()

    <footer>
        @@copy right protected
    </footer>
</body>


</html>

HMS/HMSWeb.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#999999" />
    <title>@ViewBag.Title - Shangri La</title>
    <link href="~/Content/Images/icon.ico" rel="shortcut icon" type="image/x-icon" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link href="~/Styles/Site.css" rel="stylesheet" type="text/css" />*@
</head>
<body>
    <link href="~/Styles/Site.css" rel="stylesheet" type="text/css"/>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trio-HMS ♚", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
		<ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Create","Customers")">SignUp</a></li>

                    <li><a href="@Url.Action("Index","HMSCustomer")">Login</a></li>
  
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SPS Pvt. Ltd.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>